#!/bin/sh

sleep 20

max=$(cat /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_max_freq)
max=$(cat /sys/devices/system/cpu/cpufreq/policy3/cpuinfo_max_freq)
max=$(cat /sys/devices/system/cpu/cpufreq/policy4/cpuinfo_max_freq)
max=$(cat /sys/devices/system/cpu/cpufreq/policy7/cpuinfo_max_freq)
echo "$max" > /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq
echo "$max" > /sys/devices/system/cpu/cpufreq/policy3/scaling_max_freq
echo "$max" > /sys/devices/system/cpu/cpufreq/policy4/scaling_max_freq
echo "$max" > /sys/devices/system/cpu/cpufreq/policy7/scaling_max_freq

stop="disabled"
    for zone in /sys/class/thermal/thermal_zone*; do
    if [ -f "$zone/mode" ]; then
        echo "$stop" > "$zone/mode"
   fi
done

# Override thermal limits
    for thermal_limit in /sys/class/thermal/thermal_zone*/trip_point_*_temp; do
        if [ -f "$thermal_limit" ]; then
            echo "150000" > "$thermal_limit" 2>/dev/null
        fi
    done
